# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/parag',
                'doc_host': 'https://rraadd88.github.io',
                'git_url': 'https://github.com/rraadd88/parag',
                'lib_path': 'parag'},
  'syms': { 'parag.core': {'parag.core.get_net_data': ('data.html#get_net_data', 'parag/core.py')},
            'parag.graph': { 'parag.graph.center_subset_label': ('graph.html#center_subset_label', 'parag/graph.py'),
                             'parag.graph.get_preprocessed': ('graph.html#get_preprocessed', 'parag/graph.py'),
                             'parag.graph.to_net': ('graph.html#to_net', 'parag/graph.py')},
            'parag.hypergraph': { 'parag.hypergraph.get_degreeby_subset': ('hypergraph.html#get_degreeby_subset', 'parag/hypergraph.py'),
                                  'parag.hypergraph.plot_degreeby_subset': ('hypergraph.html#plot_degreeby_subset', 'parag/hypergraph.py'),
                                  'parag.hypergraph.to_net': ('hypergraph.html#to_net', 'parag/hypergraph.py')},
            'parag.utils': { 'parag.utils._set_defaults': ('utils.html#_set_defaults', 'parag/utils.py'),
                             'parag.utils.display_plot': ('utils.html#display_plot', 'parag/utils.py'),
                             'parag.utils.export_plot': ('utils.html#export_plot', 'parag/utils.py'),
                             'parag.utils.get_colors': ('utils.html#get_colors', 'parag/utils.py'),
                             'parag.utils.get_src_path': ('utils.html#get_src_path', 'parag/utils.py')}}}
