name: CI
on:  [workflow_dispatch, pull_request, push]

permissions:
  contents: write

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: ruff
        continue-on-error: true
        run: |
          pip install --user ruff
          ruff check --fix parag
          ruff format parag
      - name: ruff commit
        continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}          
          commit_message: '[CI bot] linting and formating (ruff)'

  test:
    runs-on: ubuntu-latest
    steps: [uses: fastai/workflows/nbdev-ci@master]